plugins {
    id 'net.fabricmc.fabric-loom-remap' version '1.16-SNAPSHOT'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}


repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation("net.fabricmc:fabric-loader:${project.loader_version}")
    modImplementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")
    modImplementation("net.fabricmc:fabric-language-kotlin:1.13.12+kotlin.2.4.0")
    include(modApi "com.electronwill.night-config:core:3.8.4")
    include(modApi "com.electronwill.night-config:toml:3.8.4")
    include(modApi "com.github.twitch4j:twitch4j:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-eventsub-websocket:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-common:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-helix:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-chat:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-util:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-pubsub:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-eventsub-common:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-auth:1.26.0")
    include(modApi "com.github.twitch4j:twitch4j-client-websocket:1.26.0")
    include(modApi "com.github.philippheuer.events4j:events4j-handler-simple:0.12.3")
    include(modApi "com.github.philippheuer.events4j:events4j-core:0.12.3")
    include(modApi "com.github.philippheuer.events4j:events4j-api:0.12.3")
    include(modApi "com.github.philippheuer.credentialmanager:credentialmanager:0.4.0")
    include(modApi "io.github.openfeign:feign-core:13.8")
    include(modApi "io.github.openfeign:feign-hystrix:13.8")
    include(modApi "io.github.openfeign:feign-jackson:13.8")
    include(modApi "io.github.openfeign:feign-okhttp:13.8")
    include(modApi "io.github.openfeign:feign-slf4j:13.8")
    include(modApi "io.github.xanthic.cache:cache-api:0.7.1")
    include(modApi "io.github.xanthic.cache:cache-core:0.7.1")
    include(modApi "io.github.xanthic.cache:cache-provider-caffeine:0.7.1")
    include(modApi "com.squareup.okhttp3:okhttp:4.12.0")
    include(modApi "com.squareup.okhttp3:okhttp-jvm:5.3.2")
    include(modApi "com.squareup.okio:okio-jvm:3.16.4")
    include(modApi "com.netflix.hystrix:hystrix-core:1.5.18")
    include(modApi "com.netflix.archaius:archaius-core:0.4.1")
    include(modApi "com.bucket4j:bucket4j_jdk8-core:8.10.1")
    include(modApi "com.github.tony19:named-regexp:1.0.0")
    include(modApi "com.github.ben-manes.caffeine:caffeine:2.9.3")
    include(modApi "com.fasterxml.jackson.core:jackson-annotations:2.21")
    include(modApi "com.fasterxml.jackson.core:jackson-core:2.21.0")
    include(modApi "com.fasterxml.jackson.core:jackson-databind:2.21.0")
    include(modApi "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.21.0")
    include(modApi "commons-configuration:commons-configuration:1.10")
    include(modApi "commons-lang:commons-lang:2.6")
    include(modApi "commons-logging:commons-logging:1.1.1")
    include(modApi "com.neovisionaries:nv-websocket-client:2.14")
    include(modApi "io.reactivex:rxjava:1.2.0")
    include(modApi "org.hdrhistogram:HdrHistogram:2.1.9")


}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

